output: 'lib/src/ticore_bindings.dart'
headers:
  entry-points:
    - '../../c_api/include/taichi/taichi.h'
  include-directives:
    - '**taichi_core.h'
    - '**program.h'
    - '**frontend_ir.h'
name: 'TaichiCore'
description: 'Bindings to Taichi compiler CAPI'
comments:
  style: doxygen
  length: full

